# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# Pawtucket 2.0 - Media volumes configuration
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

images = {
    hostname = 81.0.58.152:3510,
    protocol = http,
    urlPath = /media/collectiveaccess/images,
    absolutePath = /var/www/html/media/collectiveaccess/images,
    writeable = 1,
    description = Images
}

tilepics = {
    hostname = 81.0.58.152:3510,
    protocol = http,
    urlPath = /media/collectiveaccess/tilepics,
    absolutePath = /var/www/html/media/collectiveaccess/tilepics,
    writeable = 1,
    description = Tilepic format art images
}

flv = {
    hostname = 81.0.58.152:3510,
    protocol = http,
    urlPath = /media/collectiveaccess/flv,
    absolutePath = /var/www/html/media/collectiveaccess/flv,
    writeable = 1,
    description = FLV video
}

quicktime = {
    hostname = 81.0.58.152:3510,
    protocol = http,
    urlPath = /media/collectiveaccess/quicktime,
    absolutePath = /var/www/html/media/collectiveaccess/quicktime,
    writeable = 1,
    description = QuickTime
}

windowsmedia = {
    hostname = 81.0.58.152:3510,
    protocol = http,
    urlPath = /media/collectiveaccess/windowsmedia,
    absolutePath = /var/www/html/media/collectiveaccess/windowsmedia,
    writeable = 1,
    description = WindowsMedia
}

mp3 = {
    hostname = 81.0.58.152:3510,
    protocol = http,
    urlPath = /media/collectiveaccess/mp3,
    absolutePath = /var/www/html/media/collectiveaccess/mp3,
    writeable = 1,
    description = MP3 audio
}