navigation_hierarchies = {
    global = {
        inici = {
            displayName = Inici,
            default = {
                module = ,
                controller = Front,
                action = Index
            }
        },
        arxiu = {
            displayName = Arxiu,
            default = {
                module = ,
                controller = Arxiu,
                action = Quadre
            }
        }
    }
}